name: Auto release
on:
  push:
    branches: ["master"]
    paths:
      - "src/**"
      - "src-tauri/**"
      - "/index.html"
      - "/postcss.config.js"
      - "/tailwind.config.js"
      - "/vite.config.ts"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: windows-latest
    steps:
      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          npm i -g pnpm
          pnpm i
      - name: Bump version
        run: pnpm version prerelease
      - name: Push
        run: git push
      - name: Build
        run: pnpm tauri build
      - name: Release
        run: |
          $CURRENT_VERSION="git describe --tags --abbrev=0"
          gh release create $CURRENT_VERSION "./src-tauri/target/release/bundle/*" --prerelease --notes "该发布为自动构建的预览版本。" --title $CURRENT_VERSION
